### ISSUE TITLE
Use --omit=dev when executed under node-18.x (--production is deprecated)

### ISSUE THREAD

**Issue by christian-weiss-df** [oke-py/npm-audit-action#121]

**Comment by danleedham** [comment]
Unsure if this is the same cause but running @v2+ using: 

`production_flag: true` I get the following error: 

`npm WARN config production Use `--omit=dev` instead.`

**Comment by oke-py** [comment]
@christian-weiss-df Thanks for your report.
This fix is available in v2.3.0 and v2.
