### ISSUE TITLE
Issue identified when running the 'npm-audit-action' within an Window OS

### ISSUE THREAD

**Issue by ShaidK** [oke-py/npm-audit-action#123]
**ANALYSIS OF ISSUE**

So when using the _'npm-audit-action'_ within my Private Project Workflow, the Workflow Pipeline Failed with the following Error Message stating the _'spawnSync npm ENOENT' _(See CODE 1)._

Conducting analysis on this I have found that this was an issue within Windows OS whereby specifying the '_npm_' command within the _'spawnSync'_ has failed because the '_npm_' within Windows OS is appended with '_cmd_' datatype. 

**RESOLUTION**

To fix this issue I have provided a _Ternary Operator_ which checks if the Node JS which is running on is a Windows OS _(See CODE 2)_. If it is it will use the string '_npm.cmd_' else it will use the default '_npm_' script. This is then pipe through the '_spawnSync_' which fixes this issue.

**UPDATED PIPELINE**

I have further updated the Pipelines as well to use a _OS Matrix_ in test on different operating systems (_aka ubuntu-latest, windows-latest & macos-latest_). This has been done on both _'test.yml'_ & _'daily.yml'_ scripts.

_Note - Associated [Pull Request Fix](https://github.com/oke-py/npm-audit-action/pull/122)_

**FURTHER NOTE** 

CODE 1 - _Failure within the Windows OS Actiosn_
```
dedupe_issues: false
create_issues: true
Current working directory: D:\a\Snowstorm\Snowstorm
Error: spawnSync npm ENOENT
```

CODE 2 - _Specified Ternary Operator for type OS used_
```
const isWindowsEnvironment = process.platform == "win32";
const cmd = (isWindowsEnvironment) ? 'npm.cmd' : 'npm';
```

**Comment by oke-py** [comment]
@ShaidK Thanks for your contribution. I've released v2.2.0 and updated v2.
