### ISSUE TITLE
Upgrade to using Environment Files

### ISSUE THREAD

**Issue by intervall-daniel** [oke-py/npm-audit-action#130]
**What would you like to be added**:
Please upgrade to using Environment Files.

**Why is this needed**:
I am getting this warning when using the action:
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Duceswild99** [comment]
+1

**Comment by oke-py** [comment]
@intervall-daniel Thank you for this report. v2.4.0 has just been released, and v2 is also referring this version.

**Comment by intervall-daniel** [comment]
great! thank you @oke-py!
