### ISSUE TITLE
De-dupe issues created by action

### ISSUE THREAD

**Issue by ssmall** [oke-py/npm-audit-action#60]
**What would you like to be added**:

The ability for npm-audit-action to automatically detect existing open issues that it has previously created, and avoid creating a new issue in that case.

**Why is this needed**:

When running npm-audit-action on a schedule, I do not want to create a new issue if there is already an open issue created by a previous run.

**Comment by ssmall** [comment]
I am working on a PR for this

**Comment by oke-py** [comment]
@ssmall [v1.5.0](https://github.com/oke-py/npm-audit-action/releases/tag/v1.5.0) is out. Thanks!

**Comment by ssmall** [comment]
Thank you!
