### ISSUE TITLE
Support different working directory

### ISSUE THREAD

**Issue by ssmall** [oke-py/npm-audit-action#61]
**What would you like to be added**:

Add a new input `working_directory` that sets the working directory where the `package.json` resides.

**Why is this needed**:

When I try to use npm-audit-action in a project that does not have a `package.json` in the top level directory, the action fails.

**Comment by oke-py** [comment]
@ssmall Thank you for the suggestion.
This feature is available in [v1.4.0](https://github.com/oke-py/npm-audit-action/releases/tag/v1.4.0).
Feel free to open an issue if it does not work as you expect.
