### ISSUE TITLE
Add the name of the actual working directory to the report

### ISSUE THREAD

**Issue by dominikfoldi** [oke-py/npm-audit-action#73]
**What would you like to be added**:

Add the name of the actual working directory to the report.

**Why is this needed**:

I configured the action 3 times for 3 different projects/folders in the same workflow and now I don't know which package.json has the vulnerable dependencies. Of course, I know which package.json has that dependency if I check the dependency name and then check my package.jsons but it would be nice to know this info right away from the report. Plus, imagine if somebody configures it in a monorepo for 10+ packages.

**Comment by oke-py** [comment]
#64 probably fixed this issue.
