### ISSUE TITLE
Add --production flag 

### ISSUE THREAD

**Issue by sgkiokas** [oke-py/npm-audit-action#74]
**What would you like to be added**:

It would be nice to have the option to run `npm audit` with the `--production` flag as well. I'd imagine that this should be done [here](https://github.com/oke-py/npm-audit-action/blob/107a3c4a4ac9b5c857bbbbe9e2887dc4e633ad61/src/audit.ts#L14).

**Why is this needed**:

We are looking to take advantage of this action for our repo, however, the lack of that flag will mean that our PRs will flood with potential vulnerabilities for the dev dependencies that have no real value for our production code.

P.S.: If you welcome PRs, please do let me know in order to help. Thanks!

**Comment by oke-py** [comment]
@sgkiokas It sounds good. Are you going to open a PR?

**Comment by sgkiokas** [comment]
@oke-py I'll try to as soon as I can :)

**Comment by oke-py** [comment]
This feature is added in v1.6.0.
