### ISSUE TITLE
Add a --json flag 

### ISSUE THREAD

**Issue by sgkiokas** [oke-py/npm-audit-action#76]
**What would you like to be added**:

Similarly to the https://github.com/oke-py/npm-audit-action/commit/42e6d27a296acdda53000e8062065f183fbe2ccd PR, it would be nice to have the option to run this action with a `--json` flag.

**Why is this needed**:

In case someone wants to retrieve the output of that action for further processing (e.g. reporting, integration with JIRA etc) via a custom made Github action, having the ability to get that on a JSON format is extremely useful.

**Comment by sgkiokas** [comment]
@oke-py if you want me to move on with that PR, please let me know!

**Comment by oke-py** [comment]
@sgkiokas Thank you. I've assigned this to you.

**Comment by oke-py** [comment]
This feature is available in v1.7.0. Thanks! @sgkiokas
