### ISSUE TITLE
Add an output for the npm audit in both text and json format

### ISSUE THREAD

**Issue by sgkiokas** [oke-py/npm-audit-action#77]
**What would you like to be added**:
It would be extremely useful if apart from creating a comment on a pull requests to make the npm audit result available as output to different actions using the `core.setOutput` method. 

**Why is this needed**:
The above will give the ability to combine the current action with many others that need to for further processing and/or integration. We could have 2 outputs: 1 for the normal `npm audit` result and 1 for the `npm audit --json` that will be added via https://github.com/oke-py/npm-audit-action/issues/76

**Comment by sgkiokas** [comment]
@oke-py if you agree with the above, please do let me know and I can combine it with https://github.com/oke-py/npm-audit-action/issues/76.

**Comment by oke-py** [comment]
@sgkiokas Sounds good.

**Comment by oke-py** [comment]
This feature is available in v1.7.0. Thanks! @sgkiokas
