### ISSUE TITLE
Make the issue and the PR comment optional

### ISSUE THREAD

**Issue by sgkiokas** [oke-py/npm-audit-action#80]
**What would you like to be added**:
It would be nice to add the functionality to make the creation of an issue and/or a PR comment in case a vulnerability is found optional in order to make the use of that action more flexible.

**Why is this needed**:
As described above.

**Comment by oke-py** [comment]
@sgkiokas Thank you for this request. I just published v1.8.0. Please try it and give me feedback if something is wrong.
